<?php
echo "<option>Ahmadnagar</option>
<option>Akola</option>
<option>Amravati</option>
<option>Aurangabad</option>
<option>Beed</option>
<option>Bhandara</option>
<option>Buldhana</option>
<option>Chandrapur</option>
<option>Dhule</option>
<option>Gadchiroli</option>
<option>Gondiya</option>
<option>Hingoli</option>
<option>Jalgaon</option>
<option>Jalna</option>
<option>Kolhapur</option>
<option>Latur</option>
<option>Mumbai</option>
<option>Mumbai Suburban</option>
<option>Nagpur</option>
<option>Nanded</option>
<option>Nandurbar</option>
<option>Nashik</option>
<option>Osmanabad</option>
<option>Parbhani</option>
<option>Pune</option>
<option>Raigad</option>
<option>Ratnagiri</option>
<option>Sangli</option>
<option>Satara</option>
<option>Sindhudurg</option>
<option>Solapur</option>
<option>Thane</option>
<option>Wardha</option>
<option>Washim</option>
<option>Yavatmal</option>
<option>Silvassa</option>
<option>Palghar</option>";
?>